# Generated by Django 4.1 on 2022-10-26 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archeologist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(help_text="Name", max_length=128)),
                ("surname", models.CharField(help_text="Surname", max_length=128)),
                (
                    "email",
                    models.EmailField(help_text="Email", max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name": "Archeologist",
                "verbose_name_plural": "Archeologists",
            },
        ),
        migrations.CreateModel(
            name="Artefact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Name", max_length=128)),
                (
                    "description",
                    models.CharField(
                        help_text="Description", max_length=2048, null=True
                    ),
                ),
                (
                    "creation_year",
                    models.IntegerField(
                        blank=True, help_text="Year of creation", null=True
                    ),
                ),
                (
                    "discovery_year",
                    models.IntegerField(
                        blank=True, help_text="Year of discovery", null=True
                    ),
                ),
                (
                    "archeologist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artefacts_api.archeologist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artefact",
                "verbose_name_plural": "Artefacts",
            },
        ),
        migrations.CreateModel(
            name="HistoryAge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=128)),
                (
                    "description",
                    models.CharField(
                        help_text="Description", max_length=2048, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "History Age",
                "verbose_name_plural": "History Ages",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=128)),
                ("text", models.TextField(help_text="Text")),
                ("artefacts", models.ManyToManyField(to="artefacts_api.artefact")),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AddField(
            model_name="artefact",
            name="history_age",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="artefacts_api.historyage",
            ),
        ),
    ]
