# Generated by Django 4.1 on 2022-09-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefact",
            name="archeologist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artefacts_api.archeologist",
            ),
        ),
    ]
