# Generated by Django 4.1 on 2022-10-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0002_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryAge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(help_text="Title", max_length=128)),
                (
                    "description",
                    models.CharField(
                        help_text="Description", max_length=2048, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="artefact",
            name="history_age",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="artefacts_api.historyage",
            ),
        ),
    ]
