# Generated by Django 4.1 on 2022-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0002_alter_artefact_archeologist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artefact",
            name="creation_century",
            field=models.IntegerField(
                blank=True, help_text="Century of creation", null=True
            ),
        ),
        migrations.AddField(
            model_name="artefact",
            name="discovery_year",
            field=models.IntegerField(
                blank=True, help_text="Year of discovery", null=True
            ),
        ),
    ]
