# Generated by Django 4.1 on 2022-10-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0003_artefact_creation_century_artefact_discovery_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artefact",
            name="creation_century",
        ),
        migrations.AddField(
            model_name="artefact",
            name="creation_year",
            field=models.IntegerField(
                blank=True, help_text="Year of creation", null=True
            ),
        ),
    ]
