# Generated by Django 4.1 on 2022-10-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0003_historyage_artefact_history_age"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historyage",
            options={
                "verbose_name": "History Age",
                "verbose_name_plural": "History Ages",
            },
        ),
    ]
