# Generated by Django 4.1 on 2022-10-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0004_remove_artefact_creation_century_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archeologist",
            old_name="name",
            new_name="first_name",
        ),
    ]
