# Generated by Django 4.1 on 2022-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artefacts_api", "0005_article_archeologists"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="history_ages",
            field=models.ManyToManyField(to="artefacts_api.historyage"),
        ),
    ]
