# Generated by Django 4.1 on 2022-09-04 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artefact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Name", max_length=128)),
                (
                    "description",
                    models.CharField(
                        help_text="Description", max_length=2048, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Artefact",
                "verbose_name_plural": "Artefacts",
            },
        ),
    ]
